name: Blob storage CICD

on: push

jobs:
  build:
    name: deploy files info
    runs-on: ubuntu-latest
    # if: "contains(github.event.head_commit.message, 'cicd:')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - run: go version
      - run: go run main.go

      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main
          folder: data
          clean: false
          force: false
          commit-message: update blob.json by action
