name: Blob storage CICD

on: push

jobs:
  build:
    name: deploy files info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: go version
      - run: go run main.go

      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.CDFILES }}
          folder: output
          repository-name: laof/laof.github.io
          target-folder: files
          branch: main
          commit-message: update files info by github action